- decode.go
- decode_test.go
- encode.go
- encode_test.go
- reflect.go
- sample_structs_test.go
This addresses https://github.com/gocarina/gocsv/issues/4
> Support for embedded structs

- decode.go
> Ensure that at least CSV header is present

- encode_test.go
- sample_structs_test.go
- types.go
Fix issue #5 with pointers not marshalling correctly
> Fix pointer issue

- types.go
so that `go vet` works in builds
> fix vet for unreachable code

- README.md
Took quite a bit of debugging to figure this out :P
> Fixed README first example

- csv.go
- decode.go
- decode_test.go
#85 Added Unmarshal function without using headers, instead using struct field index sequence
> Add UnmarshalWithoutHeaders function

- unmarshaller.go
This is not a API backward compatible change.
I can do it a different way if we don't want to change the
Unmarshaller API, and could make it optional if desired.
Makes Unmarshaller.MismatchedHeaders a map[int]string.
Returns a map[string]string on Unmarshaller.Read() containing the
unmatched headers and their values.
> Add Unmarshaller.ReadUnmatched() to return unmatched fields

- README.md
simplify example of custom converter in readme
> readme: simplify example

- decode.go
if block ends with a return statement, so drop this else and outdent its block.
> Remove unnecessary else block

- csv.go
- unmarshaller.go
This should give better performance.
> Use a slice in favor of a map in Unmarshaller

- unmarshaller.go
Also remove unneeded slice copy
> Make headers public on Unmarshaller

- unmarshaller.go
- unmarshaller_test.go
Also added tests for Unmarshaller
> Fixed a panic in Unmarshaller when used with FieldsPerRecord = -1

- types.go
These are worth >5% performance on one of the benchmarks.
> Add some special cases to getFieldAsString

- decode.go
My team started to use your project, which is kinda cool. I would like to propose to fix some possible issues here:
- the `readEach` func is used by `UnmarshalToChan` and `UnmarshalDecoderToChan`, which should receive a channel, and nothing else (not slice of array, it will panic otherwise). That's why I propose to assert only to `reflect.Chan` instead.
- we should receive assert type and defer channel close early before doing anything else I think, otherwise if  `decoder.getCSVRow` fails, then the channel will not be closed and there's no way to know that.
Please have a look and let me know if this PR is useful or not. Thanks..
> readEach func should assert chan kind only

- csv.go
- decode_test.go
- reflect.go
- sample_structs_test.go
Fix #117 
Added Optional custom tags.
> Support custom struct tag

- types.go
- types_test.go
Fix https://github.com/gocarina/gocsv/issues/162
Make compatible of float and int
> Make compatible of float and int

- csv.go
- encode.go
- safe_csv.go
Add CSV writer interface. It should help to use MarshalCSV without mutex and customize CSV writer behaviour.
#173
> Add CSV writer interface

- csv.go
This pull request fixes https://github.com/gocarina/gocsv/issues/178, please let me know your thoughts on this.
> Fix #178: Fix goroutine leak in UnmarshalToCallbackWithError function

- csv.go
> Update UnmarshalToCallback to allow returning an error

- decode_test.go
Thanks for the great library.
Although not a direct contribution to the functionality, I have fixed the test functions.
Reference:
- https://github.com/ipfs/kubo/issues/2043#issuecomment-164136026
- https://go.dev/ref/spec#Break_statements
> fix: call to (*T).Fatal from a non-test goroutine

- csv.go
- decode.go
Support for unmarshal multipart file into interface.
> feat: unmarshal support for multipart file added

- encode_test.go
- reflect.go
Fix this issue: https://github.com/gocarina/gocsv/issues/245
> fix: tag name issue in nested struct with child elements as struct

- decode.go
- decode_test.go
I want to use "errors.Is()" for error handling.
> add error handling

- decode.go
- encode_test.go
https://golangci-lint.run/usage/linters/#errcheck
> add to check errors

- csv.go
- decode.go
- decode_test.go
Add the ability to customize error handling for unmarshalling in channels
> Add UnmarshalToChanWithErrorHandler()
