gocarina/gocsv

- csv.go
- decode.go
- decode_test.go
- encode.go
- encode_test.go
This pull-request would allow greater control to developers to configure a csv.Writer/csv.Reader, as appropriate (e.g. create a pipe-delimited csv.Reader), without the need to modify global package state.
> Support nonglobal custom csv readwriters

- csv.go
- decode.go
- decode_test.go
This is a follow-up patch to https://github.com/gocarina/gocsv/pull/9, where a number of refactorings occurred to facilitate the work contained here.
The aim of this patch-set is to be more rigorous during csv parsing, where gocsv can fail early if expected columns, defined by annotations within the struct that gocsv is populating, don't all exist.  That is, given a csv of the form:
```
column1,column2,column3
1,2,3
4,5,6
...
```
and a corresponding struct defined as 
```go
type SomeStruct struct {
Field1 int `csv:"column1"`
Field3 int `csv:"column3"`
Field4 int `csv:"column4"`
}
```
gocsv can now error while parsing.  In contrast, previous behavior would just populate `SomeStruct.Field4` with the default zero value, and silently continue until the field is used, which usually is …
> Fail if unmatched structtags

- encode_test.go
- sample_structs_test.go
- types.go
The old code was emitting floats with 64 decimal digits of precision,
which is probably not what was intended.  Instead pass '-1' to let strconv
decide, and pass through the real precision of the value so that it makes
the right choice for the precision of value being marshaled out.
> Fix float formatting

- decode.go
- decode_test.go
This provides richer information to the consumer, allowing them to know where in the cvs the error occurred.
> Wrap type conversion errors that occur while parsing in csv.ParseErrors

- decode.go
As `i` was never incremented errors were always reported on line 2.
> Fixed line count error in readEach

- types.go
Ran into this issue while marshaling structures using gorm which uses uint for it's gorm.Model ID field.  Appears the reflect.Uint was simply missing from some of the types.go conversion cases for Uint types.
> Added reflect.Uint to types.go methods.

- types.go
- Handle "yes"/"no" the same
- Allow the empty string to default to false
- Default to built-in ParseBool
> Allow more valid values when converting string to bool

- csv.go
- decode.go
- decode_test.go
On parsing a CSV I have no control over I got confused by a repeated column header name. Imho ,similar to fail on unused struct tags, this could be optionally considered as a failure. In this branch I created a variable to enable fail on double header names and raise an error in these cases. 
Test code is also created. Please review and check if you think this is of use.
> Optional fail on double header names

- decode_test.go
- encode_test.go
- sample_structs_test.go
- types.go
When creating a non-struct type renamed from a base type, e.g. type MyFloat float64, custom defined Unmarshal/Marshal functions on this type are not executed. This branch keeps the default behaviour, aka uses the standard conversion methods if no unmarshal function is defined, but executes the function if they are defined on the type. 
Example use case: When the decimal point is not a . but a , a custom parser function is necessary. See test cases for a working example and please review for problems I might have missed.
> Support renamed types

- decode_test.go
- encode_test.go
Found a bug in the test function for (un-)marshal methods on renamed basic types. For test purposes I switch to a csv reader/writer with ; as a separator, but you will need to switch back to the default for following test functions. Found this while preparing a new feature branch/pull request. 
P.S: Sorry for bothering, there are two more pull requests to come and then everything I need for csv parsing should be covered.
> Bug fix: Switch back to default csv reader/writer after test func

- decode_test.go
- encode_test.go
- reflect.go
- sample_structs_test.go
Enable mapping of multiple header labels on a single struct field. As there already was the functionality to specify different tags on a struct field separated by , these can now be used to both be mapped on the same field.
What is this good for? I have the case where I need to parse csv files with the exact same layout, but german and english headers. Mapping two tags on the same field lets me reuse the struct.
> Multilabels

- csv.go
- decode_test.go
- reflect.go
- sample_structs_test.go
Specifying an alternative field separator should also enable the possibility to specify a separator for the struct tags. 
Example: Replacing the default csv reader with a custom one which uses ; as the field separator leads to fully valid header fields containing ,
But this mapping cannot be defined as the current implementation expects , to separate multiple csv struct tags. 
Please be aware that this pull request is based on the previous multilabel pull request.
> Tagseparator

- decode.go
- decode_test.go
- encode.go
- encode_test.go
- reflect.go
Multiple struct tags is very useful when unmarshalling from CSV, for example to map a single struct field from multiple possible source columns. It seems less useful to duplicate the same struct field data to multiple CSV columns.
This change chooses the first struct tag when marshalling to CSV. This makes it possible to add additional struct tags for unmarshalling without changing the CSV structure for marshalling.
> Use the first tag when marshalling to CSV

- decode_test.go
- encode_test.go
- sample_structs_test.go
- types.go
If a pointer field is included in the CSV file, it will receive a Go zero-value.
If a pointer field is absent from the CSV file, it will retain a nil value.
Fixes #41
> Add support for unmarshalling into pointer fields

- csv.go
- encode.go
- encode_test.go
Allows the consumer to specify to leave out the header line in the csv that is generated as brought up in issue #3
> add MarshalWithoutHeaders

- csv.go
- decode.go
This allows consumers to implement and use their own csv readers. Could be useful in the case that one wants to handle irregular rows in a special way.
> accept CSVReader interface

- csv.go
- decode.go
- decode_test.go
struct field header in the destination struct definition and test. This PR provides a way to read values in columns with duplicate headers into structs with duplicate field tags. The duplicates are matched in order from top to bottom in the struct and from left to right in the csv sheet.
> Support aligning duplicate CSV row headers with the matching duplicate

- csv.go
- encode_test.go
The library was ignoring the global TagSeparator variable when marshalling a
struct. As only one rune can be defined as a CSV separator, we are going to
trim the custom tag separator and use the first rune.
> Use TagSeparator when marshalling.

- csv.go
- decode_test.go
This just adds a bit to the previous PR: https://github.com/gocarina/gocsv/pull/47 by replacing a few occurrences of *csv.Reader with the interface CSVReader. It should let you use drop in replacements for encoding/csv in SetCSVReader and then call UnmarshalFile as usual. It works for my use case but feel free to close if it breaks something I haven't noticed.
> Use CSVReader interface instead of csv.Reader

- decode_test.go
- encode_test.go
- sample_structs_test.go
- types.go
This commit makes the order of checking `textMarshalerType` and `stringerType` interfaces more concistent. This allows working with `time.Time` and other types without custom converters.
> Improve marshalling/unmarshalling

- reflect.go
First, thanks for this awesome library! You just made my job a lot easier. Also, please be gentle. This is my first PR.
The reason for the pull request is as follows: When I was parsing a CSV, one of the column names kept getting omitted even though there was an appropriate tag on the struct I created. After some digging, I found that the header it was missing had trailing whitespace, which was causing matchesKeys to return false. I added a check for that in reflect.go, while retaining the original logic. I then ran the tests to make sure I hadn't broken anything, and the tests passed. I hope you will consider integrating this into the package itself.
Thanks!
> add handling for leading or trailing whitespace in header columns

- README.md
Hi!
I think that you forgot to fix method signature when setting gocsv.LazyCSVReader. 
Also I added example of creating reader with custom delimiter. I hope this is useful.
> Add custom delimiter and fix signature in README

- decode.go
- decode_test.go
- encode_test.go
- reflect.go
- sample_structs_test.go
- types.go
While in CSV, omitempty doesnot make much sense for writing,
during reading it can be used to skip assigning empty values.
Now on read, if the field is a pointer and the `omitempty`
tag is provided, when the value is an empty string, the
field will remain nil.
> Add support for 'omitempty' tags during decode

- types.go
- types_test.go
Replacing the [Type.Implements](https://golang.org/pkg/reflect/#Type) calls with a type assertion allows Go to cache the result of these evaluations, which leads to about a ~40% speed-up (in macOS benchmarking) when unmarshalling into a custom TypeUnmarshaller. See https://stackoverflow.com/questions/46837485/why-is-reflect-type-implements-so-much-slower-than-a-type-assertion for more background.
I found this via some 'pprof' analysis of an application that uses gocsv on fairly wide structs. Unmarshalling into custom types performed significantly more slowly than unmarshalling into native types. See https://github.com/clyphub/gocsv/pull/12.  The commit messages include some before/after benchmark outputs.
> Speed up custom type (un)marshalling

- decode.go
- unmarshaller.go
Add a Reader-like Unmarshaller that separates CSV header validation and row unmarshalling. Add detection of mismatched CSV header, which was previously ignored.
> Add a Reader-like Unmarshaller

- reflect.go
`type Sample struct {...}`
```
type EmbedSample struct {
Sample
}
```
I see no reason why an embedded struct is supported but a named struct is ignored. I've updated the code so that 
```
type EmbedSample struct {
Named Sample
}
```
will be included when encoding a csv
> allows for named structs to be included in reflection

- types.go
- this comes per request from issue:
https://github.com/gocarina/gocsv/issues/92
- trim white space since it could allow for incorrect comparison as well
e.g. 'yes ' != 'yes'
> Fix toBool() to ignore case when comparing strings

- go.mod
The latest version of go toolchain has added support for versioned
modules. This change adds a go.mod file with v2 as the version, to
enable use with vgo and the proposed go module system in the future.
I have chosen v2 as version as I see that a branch named v1 exists. If
this PR is merged, a tag named `v2.0.0` will also need to be created to
make `gocsv` work well with go module support.
> Add go.mod with v2 as module version

- go.mod
updated go.mod for migration to go module. Right now the project can't be used by go module project as the package name list is different to the import path and the github repo location. With this modification and adding a version tag like v2.0.0, the project would be usable by go module project.
Related issue:
https://github.com/gocarina/gocsv/issues/100
> add go.mod for migration to go module

- encode_test.go
- reflect.go
- sample_structs_test.go
I've noticed that this lib works improperly with my structure, so I checked and found out that in some cases line `indexChain := append(parentIndexChain, i)` in `reflect.go` was responsible for replacing of `indexChain` across same structure in multiple fields. I fixed the problem and wrote tests with my own structures to reproduce the bug
> [pull request] embeded complex structures may have invalid indexChain

- decode.go
- decode_test.go
- sample_structs_test.go
Missed updating the `setInnerField` function in last PR. enables decoding into struct pointers. my bad about missing this in the first one
> Decoding for struct pointers

- csv.go
- decode_test.go
Closes #109 
We use gocarina/gocsv for a program that supports both TSV and CSV in the same process. We need the ability to pass in a custom reader to the Unmarshal call without setting the global CSV reader. This is possible using the UnmarshalCSV function if you want headers but there was no equivalent of UnmarshalCSV for UnmarshalWithoutHeaders.
> Allow unmarshaling without headers using a custom CSV reader

- csv.go
- decode.go
- decode_test.go
This has the added side benefit of making it possible to simplify the internals of gocsv a tiny bit
> Fixes #119 -- made it possible to actually use the SimpleDecoder public interface

- csv.go
- unmarshaller.go
Comments should begin with the name of the function.
https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
> Fix function name of comment

- decode.go
Error strings should not be capitalized.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
> Uncapitalize error strings

- unmarshaller.go
**Problem:** The CSV unmarshaller throws an error if duplicate header values are used in the CSV file. This is because when `maybeDoubleHeaderNames()` is called in the validate(); it doesn't check if `FailIfDoubleHeaderNames` is enabled/disabled. 
**Solution:** Check if `FailIfDoubleHeaderNames` is enabled before calling `maybeDoubleHeaderNames()`
> add a guard for maybeDoubleHeaderNames()

- csv.go
- decode.go
- decode_test.go
- reflect.go
- unmarshaller.go
Function `normalizeName(string) string` is applied to both headers and struct field names before they are compared. Can be used to to allow case insensitive headers or headers that are not valid struct field names (e.g. change "-" to "_") that applies to all fields, without having to tag them individually.
> Added header normalizer function

- types.go
This saves a few percentage points off serialization in our application.
> Lazily-compute error message which is unlikely to ever be used

- decode_test.go
- sample_structs_test.go
- types.go
This looked very much like an oversight that switch cases in Go don't fallthrough by default, even if they don't have any code of their own, unlike in certain other languages. Using the JSON-based unmarshaling method for both structs and slices works just fine, as shown by the test I added to make sure this keeps working.
… *if* you separate your values with something else than the default comma, that is…
> Fix unmarshaling into slices

- types.go
If you pass in a struct full of `interface{}`s, only empty string is marshalled. C-style switch statements don't fall-through in Go.
> Fix switch statement fall-through bug.

- csv.go
- reflect.go
Define a new function UnmarshalBytesToCallbackWithError, which allows Callback function to return an error.
If the callabck returns an error, the callback will not be called anymore. From the caller's perspective, the processing is stopped.   
If there is any callback error, it will returned to the caller as the return value of UnmarshalBytesToCallbackWithError
> [Proposal and Sample PR] Define a new function UnmarshalBytesToCallbackWithError

- csv.go
Define the following 3 functions as a group: 
- UnmarshalToCallbackWithError
- UnmarshalBytesToCallbackWithError
- UnmarshalStringToCallbackWithError
> Define Unmarshal(xxx)ToCallbackWithError series

- csv.go
The use case is very specific, but in our side we've multiple big CSV files (~500mo), and we should retrieve dynamic headers.
CSVMaps was great but it require to load all the content into memory. This function is nearly the same as CSVMaps but accept another argument and push row into channel instead of a `[]map[string]string`
> Allow channel use with CSVToMaps

- csv.go
- encode_test.go
- reflect.go
Previously we were checking the cache, but not actually reading from it. This makes Benchmark_MarshalCSVWithoutHeaders three times faster.
> Properly cache structInfo

- decode.go
- decode_test.go
- sample_structs_test.go
- types.go
- types_test.go
I opened an issue recently asking for the ability to define a struct as have all it's fields customizable. This will reduce redundancy in needing to define separate types for fields within a struct. It also has the added benefit of allowing better abstractions in third party code dependency injections. 
Please review and confirm that the addition is sound and makes sense.
> Feature add csv interface

- decode.go
- unmarshaller.go
Extracts the following error values so that consumers of this package
can match against them with a backwards compatibility guarantee.
```go
var (
ErrEmptyCSVFile = errors.New("empty csv file given")
ErrNoStructTags = errors.New("no csv struct tags found")
)
```
> extract ErrEmptyCSVFile and ErrNoStructTags error values

- types.go
- types_test.go
String aliases with custom marshalers were being ignored and only evaluated to the string value on line 303 before the custom marshaller was being called. Removing that line respects the marshalers and they are evaluated on line 339 without custom marshalers.
> fixed marshaling of string aliases

- decode.go
Little mistake on previous PR that sum up the errors into errors objects
> fix: Wrong Error Thrown When No Fields In Struct

- csv.go
- decode_test.go
This is a generic version of CSVToMap, added in 969d259.
Also added a benchmark to compare this new function with the old CSVToMap. On my system, reflection introduces a performance drop of about 41% ([coincidence?](https://github.com/gocarina/gocsv#81)):
```
goos: windows
goarch: amd64
pkg: github.com/gocarina/gocsv
cpu: Intel(R) Core(TM) i5-8400T CPU @ 1.70GHz
BenchmarkCSVToMap-6         	442351	2409 ns/op
BenchmarkUnmarshalCSVToMap-6	284492	4089 ns/op
```
Therefore, I'm keeping the separate, non-reflection implementation of CSVToMap, rather than reimplementing it in terms of the new UnmarshalCSVToMap.
> Add an unmarshaling function for 2-column CSV into generic maps

- decode_test.go
- reflect.go
Observed no catch on variations in tag formatting, e.g. `csv:"foo, omitempty, default=16"`.  Implements light tweaks to ensure that `" , omitempty"` is treated the same as `",omitempty"` to deal with inconsistent behavior as observed in comment on #175
> Trim whitespace when parsing csv tags

- unmarshaller.go
- unmarshaller_test.go
I have a use case where a team wants to read multiple CSVs files where the header column names may not be conforming to a specific schema.
In this case we want to have a custom mapping of header names without having to do 2 passes over the file to normalize the headers.
I have added a unit test demonstrating the use case.
> feat: add header renormalization method

- csv.go
- decode.go
- decode_test.go
Export `Decoder` and `SimpleDecoder` interface methods.
Current implementation is leaving `getCSVRow` and `getCSVRows` as private methods. Therefore, we have no way to implement a custom `SimpleDecoder` from outside of this package.
```sh
golang/testpkg/csv_reader_adapter.go:31:9: cannot use &CSVDecoderAdapter{...} (type *CSVDecoderAdapter) as type gocsv.SimpleDecoder in return argument:
*CSVDecoderAdapter does not implement gocsv.SimpleDecoder (missing gocsv.getCSVRow method)
have getCSVRow() ([]string, error)
want gocsv.getCSVRow() ([]string, error)
```
References: <https://groups.google.com/g/golang-nuts/c/6hpUErAfMHI>
> Export decoder and simpleDecoder interface methods

- csv.go
- encode.go
Probably very niche in its use but I saw that most of the other functions have a `WithoutHeaders` counterpart so this is also for consistency.
> Add function to marshal to channel omitting headers

- decode.go
- decode_test.go
- encode.go
- encode_test.go
- reflect.go
- sample_structs_test.go
This makes it possible to prefix nested struct fields with the tag of the struct.
This also fixes #107 and #168
```
type NestedSample struct {
Inner1      InnerStruct       `csv:"one"`
InnerIgnore InnerStruct       `csv:"-"`
Inner2      InnerStruct       `csv:"two"`
}
type InnerStruct struct {
String string `csv:"string"`
}
```
When marshaling/unmarshaling `NestedSample` the following headers will be used:
```
one.string,two.string
```
Note: This PR builds on my first PR #207.
> Prefix fields of nested struct with tag of nested struct + .

- types.go
- unmarshaller_test.go
This PR fixes Issue #214 by short-circuiting JSON-unmarshal for structs and slices in the case where the column name is empty.
> Fixed issue with unmarshalling slice of structs that is empty

- encode_test.go
- reflect.go
- sample_structs_test.go
This pull request fixes an issue wherein `MarshalCSV` was implemented on pointers-to-structs rather than the structs themselves, causing the `writeTo` function to ignore the definition. This addresses issue #216.
> Fixed issue with MarshalCSV of pointer type not marshalling properly

- decode_test.go
- encode_test.go
- reflect.go
- sample_structs_test.go
- types.go
This comes down to not exposing the field names of nested structs as a `fieldInfo` if the struct implements `UnmarshalText` or `UnmarshalCSV`. https://github.com/gocarina/gocsv/commit/eeb477f6ec9dd44065df8d0960bc9ef37f4153ea already prevented the same if the struct implements `MarshalCSV` or `MarshalText`, but I would say that this should also be the case if just
one or both of the *unmarshaling* methods are defined.
Otherwise, an exported field from a nested structure will shadow the intended unmarshaling behavior of the top-level structure if one of its fields has the same name as a field of the nested structure itself. See the added test for an example.
Changing this doesn't break any of the existing tests.
> Allow clashing field names of nested structs to be overridden with custom unmarshalers

- README.md
Adds package name to type.
Now it works by copy-and-paste.
> Fixes example code for specified delimiter in writer

- README.md
- custom_unmarshaller_test.go
- reflect.go
- sample_structs_test.go
We auto-create structs using https://github.com/volatiletech/sqlboiler.  
And load in data using e.g. csv via gocsv.
For sqlboiler to work, they have `R` and `L` fields. Those fields are other structs (or pointer to them). And the relation can circle.
This results for some structs in infinity loops.
Respecting the csv ignore `"-"` would resolve this.  
This PR aims to do that.  
After running our code we get no more infinity loops.
example output struct
```
type Pilot struct {
ID   int    `boil:"id" json:"id" toml:"id" yaml:"id"`
Name string `boil:"name" json:"name" toml:"name" yaml:"name"`
R *pilotR `boil:"-" json:"-" toml:"-" yaml:"-"`
L pilotR  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```
Probably fixes #168
> Respect csv ignore tag

- decode_test.go
- encode_test.go
- examples/full/.gitignore
- examples/full/main.go
- examples/full/main_test.go
- reflect.go
- sample_structs_test.go
- types.go
This undoes the breaking changes knowingly caused in #210 and also fixes the minor custom unmarshaller issue that it mentions.
> Unrevert "Prefix fields of nested struct with tag of nested struct + ."

- types.go
I'm using the library for loading almost 1GB of CSVs and I try to make it as fast as possible. This was the biggest error so I would like to upstream it. It does technically break interface but I don't see a reason anyone would use this error outside of the library code itself.
> Only generate message for NoUnmarshalFuncError when needed

- decode_test.go
- reflect.go
We have a real use case where a CSV header is dynamic, like this: `Total Premium: $2,160.00`
With this change you can now mark a field as partial, and it will match any CSV headers which contains the key.
> allow "partial" keys

- encode_test.go
- reflect.go
- sample_structs_test.go
Hi,
I ran into a problem when a struct contained a CreatedAt field and one of its substruct (eg. Inner) also contained a name with the same field name. The type of both fields were time.Time.  When exported to CSV the column name of Inner was not prefixed with "Inner", so in the resulting header field list CreatedAt occured two times. 
I expected CreatedAt and Inner.CreatedAt as column names instead of CreatedAt, CreatedAt.
After some debugging I hope I was able to find the root cause and provide a fix for it. I created a test case too.
Thx, 
joe
> Fix nested non marshaling structs prefixing

- csv.go
- reflect.go
As explained on #240, it seems that the library doesn't have a feature to let devs control how the Parent.Child field tag is written.
1. Added an exported `FieldsCombiner`: allows for more flexibility/control on how parent & child struct will be combined.
Would love to hear your thoughts/feedback! :)
> feat: add flexibility for field-combiner rune

- reflect.go
- reflect_test.go
As a last way to compare keys, remove all zero-width characters from the key.
Solved #242
> Remove zero-width chars from key, before matches

- encode_test.go
- reflect.go
- sample_structs_test.go
For a field that is simply a slice or an array of a Struct, if no special `csv[]` tag is supplied, just marshal the array elements to string, encoded into the csv column.
This won't interfere with the csv[] field expansion logic.
> fix: handle slice/array of Struct when csv[] tag missing

- csv.go
- csv_test.go
I've added a testcase for this situation. Current implementation will just ignore pending error.
It should be safe to use pure read of cerr chans in these cases. Functions reach final return statements only when c is closed. So UnmarshalToChan returned successfully and wrote to cerr.
> UnmarshalToCallback functions don't return reader's error

- decode.go
- decode_test.go
- sample_structs_test.go
- Add support for calling TypeUnmarshalCSVWithFields interface in readEach function similar to readTo
- Slight rearrangment of calling UnmarshalCSVWithFields for both readEach and readTo to place it above the fieldInfo check
- A type should be able to completely handle unmarshalling by implementing this interface, it doesn't seem like it should depend on having csv tags matching the headers or not
- This allows, for example, a csv record to be read into a struct with unknown headers; extra columns could be added to a map field in the struct, etc
- Also add missing default value setting in readEach
> Support TypeUnmarshalCSVWithFields in readEach
